### ISSUE TITLE
bot crashed. stacktrace in comment

### ISSUE THREAD

**Issue by hennobit** [hennobit/discord-lurker#6]
Unhandled exception in internal background task 'scan_server'.
Traceback (most recent call last):
  File "main.py", line 27, in scan_server
    update_user_data(
  File "database_controller.py", line 99, in update_user_data
    update_online_status_time(user_id=member.id, status=str(
  File "database_controller.py", line 214, in update_online_status_time
    last_status_change = date_string_to_date(last_status_change)
  File "", line 18, in date_string_to_date
    return datetime.datetime.strptime()
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2023-10-15 17:24:03' does not match format '%Y-%m-%d %H:%M:%S.%f'

occurred for the first time so far

**Comment by hennobit** [comment]
implemented a fallback in commit 35147ec
